name: Ubuntu
on: [push]
jobs:
  Bionic:
    container: 
      image: swift:5.1.3-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Dependencies
      run: swift package update
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery
